version: "3"

networks:
  pfa-proxy-network:
  pfa-db-network:

services:
  mysql:
    image: mysql:5.7
    container_name: pfa-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - pfa-db-network

  node:
    image: node:16.10.0-alpine3.14
    container_name: pfa-node
    working_dir: /usr/src/app
    command: sh -c "
      apk update && apk add wget &&
      wget https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz &&
      tar -C /usr/local/bin -xzvf dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz &&
      rm dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz &&
      dockerize -wait tcp://pfa-mysql:3306 -timeout 50s &&
      npm install && node index.js"
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    networks:
      - pfa-proxy-network
      - pfa-db-network

  nginx:
    image: nginx:1.9.15-alpine
    container_name: pfa-nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8000:80"
    depends_on:
      - node
    networks:
      - pfa-proxy-network
