version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: pfa-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root

  node:
    container_name: pfa-node
    build: ./node
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - mysql

  nginx:
    container_name: pfa-nginx
    build: ./nginx
    ports:
      - "8080:80"