version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: pfa-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root

  node:
    image: node:16.10.0-alpine3.14
    container_name: pfa-node
    working_dir: /usr/src/app
    command: sh -c "npm install && node index.js"
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql

  nginx:
    image: nginx:1.9.15-alpine
    container_name: pfa-nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"